language: android
android:
  components:
    - build-tools-21.1.2
    - build-tools-22.0.1
    - build-tools-23.0.2
    - build-tools-23.0.3
    - tools
    - build-tools-25.0.0
    - extra-android-support
    - doc-24
    - extra
    - extra-android-m2repository
    - extra-google-m2repository
    - android-6
    - android-7
    - android-4.4
    - android-4.0
    - android-4.2
    - source-24
    - source 23
    - source-19
    - source-17
    - source 14
    - addons-google_apis-google-14
    - addon-google_apis-google-19
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
script:
  - ./gradlew build connectedCheck
  - ./gradlew build connectedCheck --stacktrace
  - ./gradlew build connectedCheck --info
  - ./gradlew build connectedCheck --debug

    - $HOME/.gradle/wrapper/
